Test--Anchore SBOM source code scan:
  stage: scan
  allow_failure: true
  variables:
    iiidevops: anchore-code
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-sbom-code"
    CHART_VERSION: "0.1.7"
  script:
    - helm uninstall -n ${CI_PROJECT_NAME} ${CHART_NAME} --cascade orphan || exit_code=$?
    - helm install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/scan-anchore
      --set anchore.image=${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}
      --set anchore.bot_user=${HARBOR_ROBOT}
      --set anchore.bot_password=${HARBOR_ROBOT_SECRET}
      --set pipeline.sequence=${CI_PIPELINE_ID}${CI_JOB_ID} 
      --set anchore.type=folder
      --version ${CHART_VERSION}
  only:
    - skip
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
