Test--Anchore SBOM source code scan:
  stage: scan
  extends: .scan-job
  allow_failure: true
  image:
    name: $HARBOR_URL/dockerhub/iiiorg/anchore-runner:2.10.0
  variables:
    iiidevops: anchore-code
    SCAN_TYPE: folder
    GRYPE_DB_CACHE_DIR: /mnt/cache/anchore
  script:
    - startup.sh
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_ANCHORE_CODE'
      when: on_success

