Test--Checkmarx source code scan:
  stage: scan
  extends:
    - .default
  allow_failure: true
  variables:
    iiidevops: checkmarx
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-cmx"
    CHART_VERSION: 2.1.2
  script:
    - 'curl -s -L -X POST ${IIIDEV_URL}/checkmarx/queue -H "Content-Type:
      application/json" -H "Authorization: Bearer $TOKEN" -d ''{ "project_name": "''"${CI_PROJECT_NAME}"''",
      "branch": "''"${CI_COMMIT_BRANCH}"''","commit":"''"${CI_COMMIT_SHORT_SHA}"''", "sequence":"''"${CI_PIPELINE_ID}"''",
      "chart_version":"''"${CHART_VERSION}"''", "chart_name":"''"scan-checkmarx"''"
      }'''
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$PLG_CHECKMARX == "false"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_CHECKMARX'
      when: on_success

