Test--Check-CN scan:
  variables:
    iiidevops: checkcn
    CHECK_CN_TAG: 1.3.0
    CHECK_CN_IMAGE: harbor.demo.iiidevops.org/iiiorg/check-cn-tool
  stage: scan
  image: ${CHECK_CN_IMAGE}:${CHECK_CN_TAG}
  script:
    - cp -f iiidevops/check-cn/traditional.txt /traditional.txt 2>/dev/null || true
    - cp -f iiidevops/check-cn/blacklist.txt /blacklist.txt 2>/dev/null || true
    - perl /usr/src/app/check-cn.pl --exclude iiidevops --traditional /traditional.txt --blacklist /blacklist.txt .
  allow_failure: false
  rules:
  - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
    when: never  
  - if: $CI_COMMIT_BRANCH =~ $III_CHECKCN
    when: always