Clean--Cache:
  stage: build
  image: alpine
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Cleaning cache..."
    - rm -rf ./*
    - ls -alh
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - "**"
    policy: push
  allow_failure: true
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$PLG_SONARQUBE == "false"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_SONARQUBE'
      when: on_success