# Job start here
default:
  image:
    name: alpine/k8s:1.25.16
    entrypoint: [ "" ]
  interruptible: true
  before_script:
    - kubectl config get-contexts
    - kubectl config use-context $(kubectl config get-contexts -o name)
    - |
      cat <<EOF >common.yaml
      pipeline:
        sequence: 0
        timeout: 3600
        ttlSecondsAfterFinished: null
        backoffLimit: 3
      api:
        url: "${IIIDEV_URL}"
        username: "${BOT_USERNAME}"
        password: "${BOT_PASSWORD}"
      git:
        url: "${CI_PROJECT_URL}.git"
        repoName: "${CI_PROJECT_NAME}"
        branch: "${CI_COMMIT_BRANCH}"
        commitID: "${CI_COMMIT_SHORT_SHA}"
        token: "${GITLAB_TOKEN}"
      harbor:
        host: "${HARBOR_URL}"
      timezone:
        tz: Asia/Taipei
      EOF
