# Job start here
default:
  interruptible: true

.default:
  image:
    name: alpine/k8s:1.25.16
    entrypoint: [ "" ]
  before_script:
    - apk add --update curl
    - 'TOKEN="$(curl -s -L -X POST ${IIIDEV_URL}/user/login -H "Content-Type: application/json"
      -d ''{"username": "''"${BOT_USERNAME}"''","password":"''"${BOT_PASSWORD}"''"}''
      | jq -r ''.data.token'')"'
    - 'SA_TOKEN="$(curl -s -L -X POST ${IIIDEV_URL}/v2/user/k8s_token -H "Content-Type:
      application/json" -H "Authorization: Bearer $TOKEN" | jq -r ''.data.token'')"'
    - kubectl config set-cluster runner-cluster --server=https://kubernetes.default.svc.cluster.local --insecure-skip-tls-verify=true
    - kubectl config set-credentials runner-bot --token=${SA_TOKEN}
    - kubectl config set-context runner --cluster=runner-cluster --user=runner-bot
    - kubectl config get-contexts
    - kubectl config use-context runner
    - |
      cat <<EOF >common.yaml
      pipeline:
        sequence: 0
        timeout: 3600
        ttlSecondsAfterFinished: null
        backoffLimit: 3
      api:
        url: "${IIIDEV_URL}"
        username: "${BOT_USERNAME}"
        password: "${BOT_PASSWORD}"
      git:
        url: "${CI_PROJECT_URL}.git"
        repoName: "${CI_PROJECT_NAME}"
        branch: "${CI_COMMIT_BRANCH}"
        commitID: "${CI_COMMIT_SHORT_SHA}"
        token: "${GITLAB_TOKEN}"
      harbor:
        host: "${HARBOR_URL}"
      timezone:
        tz: Asia/Taipei
      EOF

.scan-job:
  variables:
    git_url: "${CI_PROJECT_URL}.git"
    git_repo: "${CI_PROJECT_NAME}"
    git_token: "${GITLAB_TOKEN}"
    git_branch: "${CI_COMMIT_BRANCH}"
    git_commit_id: "${CI_COMMIT_SHORT_SHA}"
    api_origin: "${IIIDEV_URL}"
    username: "${BOT_USERNAME}"
    password: "${BOT_PASSWORD}"
    api_username: "${BOT_USERNAME}"
    api_password: "${BOT_PASSWORD}"
