Deploy--Web:
  stage: deploy
  variables:
    iiidevops: deploy
    CHART_WEB_PORT: 80
    CHART_PROXY_BODY_SIZE: 1m
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv"
    CHART_DB_NAME: "db_name"
    CHART_DB_USERNAME: "db_username"
    CHART_DB_PASSWORD: "db_passwd"
    CHART_DB_SERVER: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-db"
    CHART_VOLUME_ENABLED: "false"
    CHART_VOLUME_PATH: "/mnt/data"
    CHART_VERSION: "1.0.1"
  script:
    - helm upgrade --install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/web
      --set imagePullSecrets[0].name=harbor-local
      --set web.imageTag=${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}
      --set web.port=${CHART_WEB_PORT}
      --set db.name=${CHART_DB_NAME}
      --set db.username=${CHART_DB_USERNAME}
      --set db.password=${CHART_DB_PASSWORD}
      --set db.releaseName=${CHART_DB_SERVER}
      --set kube.ingress.base_domain=${IIIDEV_ING}
      --set kube.ingress.proxy_body_size=${CHART_PROXY_BODY_SIZE}
      --set persistence.enabled=${CHART_VOLUME_ENABLED}
      --set persistence.mountPath=${CHART_VOLUME_PATH}
      --version ${CHART_VERSION}  
    - 'curl -s -L -X POST ${IIIDEV_URL}/project/${CI_PROJECT_NAME}/pipeline 
      -H "Content-Type: application/json" 
      -H "Authorization: Bearer $TOKEN" 
      -d ''{
        "branch": "''"${CI_COMMIT_BRANCH}"''",
        "commit_id":"''"${CI_COMMIT_SHORT_SHA}"''",
        "pipeline_id":"''"${CI_PIPELINE_ID}"''",
        "job_id":"''"${CI_JOB_ID}"''",
        "job_type":"''"web"''",
        "run_web_success":"''"true"''",
        "image_path":"''"${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}"''"
      }'''
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_DEPLOY'
      when: always