Test--SonarQube source code scan:
  stage: scan
  allow_failure: true
  variables:
    iiidevops: sonarqube
    CHART_TYPE: normal
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-sq"
    CHART_VERSION: "2.0.0"
  script:
    - helm delete -n ${CI_PROJECT_NAME} ${CHART_NAME} || exit_code=$?
    - helm install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/scan-sonarqube
      --set sonarqube.url=${SONAR_URL}
      --set sonarqube.token=${SONAR_TOKEN}
      --set type=${CHART_TYPE}
      --version ${CHART_VERSION}
  only:
    - skip
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
