Test--Anchore SBOM:
  stage: test
  extends: .scan-job
  allow_failure: true
  image:
    name: $HARBOR_URL/dockerhub/iiiorg/anchore-runner:2.10.0
  variables:
    iiidevops: anchore
    SCAN_TYPE: image
    SCAN_IMAGE: "$HARBOR_URL/${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}"
    GRYPE_DB_CACHE_DIR: /mnt/cache/anchore
  script:
    - startup.sh $SCAN_IMAGE
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_ANCHORE'
      when: on_success
