Test--WebInspect:
  stage: test
  extends: .scan-job
  allow_failure: true
  image: $HARBOR_URL/dockerhub/iiiorg/webinspect-runner:5.1.0
  # TODO: update runner image
  variables:
    iiidevops: webinspect
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-test-webinspect"
    CHART_VERSION: "0.4.1"
    project_name: ${CI_PROJECT_NAME}
    target_origin: "https://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}.${IIIDEV_ING}"
    scan_policy_name: "OWASP Top 10 2021"
    wi_scc_url: ${WIE_SCC_URL}
    wi_dast_url: ${WIE_DAST_URL}
    wi_username: ${WIE_USER}
    wi_password: ${WIE_PASSWORD}
  script:
    - echo $target_origin
    - start-scan
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_WEBINSPECT'
      when: on_success
