Test--Postman:
  stage: test
  extends: .scan-job
  allow_failure: true
  image:
    name: $HARBOR_URL/dockerhub/iiiorg/newman-runner:4.2.0
  variables:
    iiidevops: postman
    CHART_WEB_PORT: 80
    test_origin: "http://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv-svc.${CI_PROJECT_NAME}.svc.cluster.local:${CHART_WEB_PORT}"
    verbose: "true"
    TZ: "Asia/Taipei"
  script:
    - node /workdir/app.js
  rules:
    - if: '$PLG_POSTMAN == "false"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_POSTMAN'
      when: on_success