Test--Sideex:
  stage: test
  extends: .scan-job
  allow_failure: true
  image:
    name: $HARBOR_URL/dockerhub/iiiorg/sideex-runner:2.11.0
    entrypoint: [ "" ]
  variables:
    iiidevops: sideex
    CHART_WEB_PORT: 80
    SELENIUM_CHROME_VERSION: '123.0'
    target_origin: "http://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv-svc.${CI_PROJECT_NAME}.svc.cluster.local:${CHART_WEB_PORT}"
    verbose: "true"
    TZ: "Asia/Taipei"
    LANG: "zh_TW.UTF-8"
    LANGUAGE: "zh_TW:zh"
    LC_ALL: "zh_TW.UTF-8"
  services:
    - name: selenium/standalone-chrome:${SELENIUM_CHROME_VERSION}
      alias: chrome
  script:
    - node /workdir/app.js
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$PLG_SIDEEX == "false"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_SIDEEX'
      when: on_success
