Test--ZAP:
  stage: test
  extends: .scan-job
  allow_failure: true
  image:
    name:   $HARBOR_URL/dockerhub/iiiorg/zap-runner:2.12.1
    entrypoint: [ "" ]
  variables:
    iiidevops: zap
    CHART_WEB_PORT: 80
    TARGET_URL: "http://${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv-svc.${CI_PROJECT_NAME}.svc.cluster.local:${CHART_WEB_PORT}"
    TZ: "Asia/Taipei"
  before_script: []
  script:
    - start-up
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: '$PLG_ZAP == "false"'
      when: never
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_ZAP'
      when: on_success
