Test--Postman:
  stage: test
  allow_failure: true
  variables:
    iiidevops: postman
    CHART_WEB_PORT: 80
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-pm"
    CHART_VERSION: "0.3.6"
  script:
    - helm uninstall -n ${CI_PROJECT_NAME} ${CHART_NAME} --cascade orphan || exit_code=$?
    - helm install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/test-postman
      --set web.deployName=${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv
      --set web.port=${CHART_WEB_PORT}
      --version ${CHART_VERSION}
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
      when: never
    - if: '$CI_COMMIT_BRANCH =~ $III_POSTMAN'
      when: always
