Test--Anchore SBOM:
  stage: test
  allow_failure: true
  variables:
    iiidevops: anchore
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-sbom"
    CHART_VERSION: "0.1.2"
  script:
    - helm delete -n ${CI_PROJECT_NAME} ${CHART_NAME} || exit_code=$?
    - helm install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/scan-anchore
      --set anchore.image=${CI_PROJECT_NAME}/${CI_COMMIT_BRANCH}:${CI_COMMIT_SHORT_SHA}
      --set anchore.bot_user=${HARBOR_ROBOT}
      --set anchore.bot_password=${HARBOR_ROBOT_SECRET}
      --version ${CHART_VERSION}
  only:
    - skip
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
