Test--WebInspect:
  stage: test
  allow_failure: true
  variables:
    iiidevops: webinspect
    CHART_NAME: "${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-test-webinspect"
    CHART_VERSION: "0.4.1"
  script:
    - helm uninstall -n ${CI_PROJECT_NAME} ${CHART_NAME} --no-hooks || exit_code=$?
    - helm install -n ${CI_PROJECT_NAME} ${CHART_NAME} -f common.yaml
      ${HARBOR_CHART_REGISTRY}/test-webinspect
      --set web.deployName=${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}-serv
      --set webinspect.URL=${WIE_URL}
      --set webinspect.dastUrl=${WIE_DAST_URL}
      --set webinspect.sccUrl=${WIE_SCC_URL}
      --set webinspect.user=${WIE_USER}
      --set webinspect.password=${WIE_PASSWORD}
      --set webinspect.type=${WIE_TYPE}
      --version ${CHART_VERSION}
  only:
    - skip
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /.*\(store\)$/
