stages:
  - initial
  - scan
  - aiwork
  - build
  - deploy
  - test

include:
  - local: 'job/DefaultJob.gitlab-ci.yml'
  - local: 'job/Initial.gitlab-ci.yml'
  - local: 'job/Sonarqube.gitlab-ci.yml'
  - local: 'job/Semgrep.gitlab-ci.yml'
  - local: 'job/Checkmarx.gitlab-ci.yml'
  - local: 'job/AnchoreForder.gitlab-ci.yml'
  - local: 'job/BuildImage.gitlab-ci.yml'
  - local: 'job/DockerScan.gitlab-ci.yml'
  - local: 'job/SetWebEnvironments.gitlab-ci.yml'
  - local: 'job/DeployWeb.gitlab-ci.yml'
  - local: 'job/DeployService.gitlab-ci.yml'
  - local: 'job/TestAnchore.gitlab-ci.yml'
  - local: 'job/TestSideex.gitlab-ci.yml'
  - local: 'job/TestPostman.gitlab-ci.yml'
  - local: 'job/TestWebInspect.gitlab-ci.yml'
  - local: 'job/TestZap.gitlab-ci.yml'
  - local: 'job/CheckCN.gitlab-ci.yml'
  - local: 'job/CleanCache.gitlab-ci.yml'